import {listPrograms,getProgram,saveProgram,deleteProgram} from './storage.js';
import {WorkoutEngine} from './workout.js';
import {BeepEngine} from './audio.js';
import {normalizeProgram,formatTime,shortTime,clamp} from './programTimeline.js';
import * as UI from './ui.js';

const state={programs:[],currentProgram:null};
const audio=new BeepEngine(); const engine=new WorkoutEngine(audio);
let saveTimer=null; let mobileNavOpen=false;
const freshSet=()=>({id:crypto.randomUUID(),duration:60,breakDuration:30,midpointBeep:true,repetitions:1});
const freshProgram=()=>({id:crypto.randomUUID(),name:'Untitled Program',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),sets:[freshSet()]});

async function init(){
  try{state.programs=await listPrograms()}catch(e){showMessage('Storage error','IndexedDB could not be initialized. Your browser may be blocking local storage. The workout can still run for this session.');state.programs=[]}
  UI.renderMetrics(state.programs); renderRecent(); renderSaved(); setupNavigation(); setupProgramActions(); setupWorkoutActions(); setupEditorEvents(); setupRepeatDialog(); await restoreState();
}
function showToast(msg){const t=UI.$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.classList.remove('show'),2500)}
function showMessage(title,body){UI.$('#messageTitle').textContent=title;UI.$('#messageBody').textContent=body;UI.$('#messageDialog').showModal()}
function renderRecent(){UI.renderProgramList(UI.$('#recentPrograms'),state.programs,id=>openProgram(id));UI.$('#recentEmpty').classList.toggle('hidden',state.programs.length>0)}
function renderSaved(){UI.$('#programCountBadge').textContent=state.programs.length;UI.renderSavedPrograms(UI.$('#savedProgramsList'),state.programs,state.currentProgram?.id,{open:openProgram,start:startWorkoutFromId,start: startWorkoutFromId,menu:programMenu})}
function programMenu(id){const p=state.programs.find(x=>x.id===id);if(!p)return;const action=window.prompt(`Actions for “${p.name}”\n\nType: rename, duplicate, or delete`,'');if(!action)return;const a=action.trim().toLowerCase();if(a==='rename')renameProgram(p);else if(a==='duplicate')duplicateProgram(p);else if(a==='delete')removeProgram(p.id)}
async function renameProgram(p){const n=window.prompt('Program name',p.name);if(!n?.trim())return;p.name=n.trim();p.updatedAt=new Date().toISOString();await persist(p);openProgram(p.id);showToast('Program renamed')}
async function duplicateProgram(p){const copy=structuredClone(p);copy.id=crypto.randomUUID();copy.name=`${p.name} Copy`;copy.createdAt=new Date().toISOString();copy.updatedAt=copy.createdAt;copy.sets.forEach(s=>s.id=crypto.randomUUID());await persist(copy);openProgram(copy.id);showToast('Program duplicated')}
async function removeProgram(id){const p=state.programs.find(x=>x.id===id);if(!p)return;if(!confirm(`Delete “${p.name}”? This cannot be undone.`))return;await deleteProgram(id);state.programs=state.programs.filter(x=>x.id!==id);if(state.currentProgram?.id===id){state.currentProgram=null;clearEditor()}UI.renderMetrics(state.programs);renderRecent();renderSaved();updateWorkoutPrograms();showToast('Program deleted')}
async function persist(p){await saveProgram(p);const i=state.programs.findIndex(x=>x.id===p.id);if(i<0)state.programs.unshift(p);else state.programs[i]=structuredClone(p);state.programs.sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));UI.renderMetrics(state.programs);renderRecent();renderSaved();updateWorkoutPrograms()}
function setupNavigation(){UI.$$('[data-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.route)));UI.$('#mobileNavToggle').addEventListener('click',()=>{mobileNavOpen=!mobileNavOpen;UI.$('.main-nav').style.display=mobileNavOpen?'flex':''})}
function navigate(route){UI.$$('.view').forEach(v=>v.classList.remove('active'));UI.$(`#${route}View`).classList.add('active');UI.$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.route===route));if(route==='workout')updateWorkoutPrograms()}
function setupProgramActions(){UI.$('#dashboardCreateBtn').addEventListener('click',newProgram);UI.$('#newProgramBtn').addEventListener('click',newProgram);UI.$('#editorNewBtn').addEventListener('click',newProgram);UI.$('#emptyCreateBtn').addEventListener('click',newProgram);UI.$('#dashboardStartBtn').addEventListener('click',()=>state.programs[0]?startWorkoutFromId(state.programs[0].id):newProgram());UI.$('#workoutCreateBtn').addEventListener('click',newProgram);UI.$('#quickRepeatBtn').addEventListener('click',()=>{newProgram();setTimeout(()=>openRepeatDialog(),0)});UI.$('#addSetBtn').addEventListener('click',()=>{if(!state.currentProgram)return;state.currentProgram.sets.push(freshSet());touchEditor()});UI.$('#repeatBlockBtn').addEventListener('click',openRepeatDialog);UI.$('#saveProgramBtn').addEventListener('click',()=>saveCurrent(true));UI.$('#previewProgramBtn').addEventListener('click',()=>state.currentProgram&&startWorkoutFromId(state.currentProgram.id,true));UI.$('#programName').addEventListener('input',()=>{if(!state.currentProgram)return;state.currentProgram.name=UI.$('#programName').value;touchEditor()})}
function setupEditorEvents(){}
function newProgram(){state.currentProgram=freshProgram();navigate('programs');renderEditor();showToast('New program ready')}
function openProgram(id){const p=state.programs.find(x=>x.id===id);if(!p)return;state.currentProgram=structuredClone(p);navigate('programs');renderEditor()}
function clearEditor(){UI.$('#editorEmpty').classList.remove('hidden');UI.$('#editorContent').classList.add('hidden')}
function renderEditor(){if(!state.currentProgram)return clearEditor();UI.$('#editorEmpty').classList.add('hidden');UI.$('#editorContent').classList.remove('hidden');UI.$('#programName').value=state.currentProgram.name;UI.renderSets(UI.$('#setsList'),state.currentProgram,{change:changeSet,duplicate:dupSet,delete:delSet,move:moveSet});UI.renderTimeline(UI.$('#programTimeline'),state.currentProgram);renderSaved();UI.$('#programSaveState').textContent='Saved locally';scheduleAutoSave()}
function touchEditor(){state.currentProgram.updatedAt=new Date().toISOString();renderEditor();UI.$('#programSaveState').textContent='Saving…';scheduleAutoSave()}
function scheduleAutoSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveCurrent(false),500)}
async function saveCurrent(manual=false){if(!state.currentProgram)return;state.currentProgram.name=(state.currentProgram.name||'Untitled Program').trim()||'Untitled Program';state.currentProgram.updatedAt=new Date().toISOString();try{await persist(structuredClone(state.currentProgram));UI.$('#programSaveState').textContent='Saved locally';if(manual)showToast('Program saved')}catch{showMessage('Save failed','The program could not be saved to this browser. Try again or check browser storage permissions.')}}
function changeSet(i,field,el){const s=state.currentProgram.sets[i];if(!s)return;if(field==='durationMin')s.duration=Math.max(0,Number(el.value||0)*60+(s.duration%60));if(field==='durationSec')s.duration=Math.max(0,Math.floor(s.duration/60)*60+clamp(Number(el.value||0),0,59));if(field==='breakMin')s.breakDuration=Math.max(0,Number(el.value||0)*60+(s.breakDuration%60));if(field==='breakSec')s.breakDuration=Math.max(0,Math.floor(s.breakDuration/60)*60+clamp(Number(el.value||0),0,59));if(field==='repetitions')s.repetitions=Math.max(1,Math.min(500,Math.floor(Number(el.value)||1)));if(field==='midpointBeep')s.midpointBeep=el.checked;touchEditor()}
function dupSet(i){const clone=structuredClone(state.currentProgram.sets[i]);clone.id=crypto.randomUUID();state.currentProgram.sets.splice(i+1,0,clone);touchEditor();showToast('Set duplicated')}
function delSet(i){if(state.currentProgram.sets.length===1){showMessage('Keep one set','A program needs at least one set. You can make its work and break durations zero if needed.');return}state.currentProgram.sets.splice(i,1);touchEditor();showToast('Set deleted')}
function moveSet(from,to){const [x]=state.currentProgram.sets.splice(from,1);state.currentProgram.sets.splice(to,0,x);touchEditor()}
function setupRepeatDialog(){UI.$('#repeatForm').addEventListener('submit',e=>{const fd=new FormData(e.currentTarget);const count=Math.max(1,Math.min(500,Number(fd.get('count'))||1));const duration=Math.max(0,Number(fd.get('minutes')||0)*60+clamp(Number(fd.get('seconds')||0),0,59));const breakDuration=Math.max(0,Number(fd.get('breakMinutes')||0)*60+clamp(Number(fd.get('breakSeconds')||0),0,59));const midpoint=fd.get('midpoint')==='on';if(!state.currentProgram)return;const made=Array.from({length:count},()=>({id:crypto.randomUUID(),duration,breakDuration,midpointBeep:midpoint,repetitions:1}));state.currentProgram.sets.push(...made);touchEditor();showToast(`${count} sets generated`)})}
function openRepeatDialog(){if(!state.currentProgram){newProgram();setTimeout(openRepeatDialog,20);return}UI.$('#repeatDialog').showModal()}
async function restoreState(){const last=localStorage.getItem('pulseset_last_program');if(last&&state.programs.some(p=>p.id===last))state.currentProgram=structuredClone(await getProgram(last));if(state.currentProgram)renderEditor();updateWorkoutPrograms()}
function updateWorkoutPrograms(){const sel=UI.$('#workoutProgramSelect');const empty=UI.$('#workoutEmpty');const stage=UI.$('#workoutStage');if(!state.programs.length){sel.innerHTML='';empty.classList.remove('hidden');stage.classList.add('hidden');return}empty.classList.add('hidden');stage.classList.remove('hidden');sel.innerHTML=state.programs.map(p=>`<option value="${p.id}" ${state.currentProgram?.id===p.id?'selected':''}>${UI.escapeHtml(p.name)}</option>`).join('');const p=state.programs.find(x=>x.id===sel.value)||state.programs[0];if(!engine.program||engine.program.id!==p.id)engine.load(p);UI.$('#workoutProgramSubtitle').textContent=p.name}
async function startWorkoutFromId(id,preview=false){const p=state.programs.find(x=>x.id===id);if(!p)return;state.currentProgram=structuredClone(p);localStorage.setItem('pulseset_last_program',id);updateWorkoutPrograms();UI.$('#workoutProgramSelect').value=id;navigate('workout');try{await audio.init()}catch(e){showMessage('Beep audio unavailable','The timer will still work, but this browser cannot provide Web Audio beeps.');audio.setMuted(true);UI.$('#muteToggle').checked=true;UI.$('#audioStatus').innerHTML='<span class="status-dot" style="background:var(--danger)"></span><span>Audio unavailable</span>'}engine.load(p);if(preview||true)engine.start()}
function setupWorkoutActions(){engine.addEventListener('tick',e=>renderWorkout(e.detail));engine.addEventListener('state',()=>renderWorkoutControls());UI.$('#workoutProgramSelect').addEventListener('change',()=>{const id=UI.$('#workoutProgramSelect').value;const p=state.programs.find(x=>x.id===id);if(p){state.currentProgram=structuredClone(p);localStorage.setItem('pulseset_last_program',id);engine.load(p);UI.$('#workoutProgramSubtitle').textContent=p.name;renderWorkoutControls()}});UI.$('#mainWorkoutBtn').addEventListener('click',async()=>{try{await audio.init()}catch{} if(engine.state==='running')engine.pause();else if(engine.state==='ready'||engine.state==='paused')engine.startOrResume();else if(engine.state==='complete'){engine.restart();engine.startOrResume()}});UI.$('#previousBtn').addEventListener('click',()=>engine.previous());UI.$('#nextBtn').addEventListener('click',()=>engine.skip(1));UI.$('#restartBtn').addEventListener('click',()=>engine.restart());UI.$('#stopBtn').addEventListener('click',()=>engine.stop());UI.$('#muteBtn').addEventListener('click',()=>toggleMute());UI.$('#muteToggle').addEventListener('change',()=>toggleMute(UI.$('#muteToggle').checked));UI.$('#volumeSlider').addEventListener('input',e=>{audio.setVolume(Number(e.target.value)/100);UI.$('#volumeValue').textContent=`${e.target.value}%`})}
function toggleMute(force){const m=typeof force==='boolean'?force:!audio.muted;audio.setMuted(m);UI.$('#muteToggle').checked=m;UI.$('#muteBtn').textContent=m?'Unmute':'Mute';UI.$('#audioStatus').innerHTML=`<span class="status-dot" style="background:${m?'#ffb454':'var(--accent-2)'}"></span><span>${m?'Beeps muted':'Beeps on'}</span>`}
function renderWorkout(d){const total=d.totalDuration;if(!d.item)return;UI.$('#workoutSetLabel').textContent=`SET ${d.currentSet+1} / ${state.currentProgram?.sets.reduce((s,x)=>s+Math.max(1,Math.floor(Number(x.repetitions)||1)),0)||1}${d.totalReps>1?` · REP ${d.currentRep}/${d.totalReps}`:''}`;UI.$('#workoutPhaseLabel').textContent=d.currentPhase==='break'?'BREAK':'WORK';UI.$('#timerRemaining').textContent=formatTime(d.currentPhase==='break'?d.setRemaining:d.setRemaining);UI.$('#setElapsedLabel').textContent=`${d.currentPhase==='break'?'Break':'Set'} elapsed ${formatTime(d.setElapsed)}`;UI.$('#setRemainingLabel').textContent=`${d.currentPhase==='break'?'Break':'Set'} ${formatTime(d.setRemaining)}`;UI.$('#overallElapsedLabel').textContent=`${formatTime(d.elapsed)} elapsed`;UI.$('#overallTotalLabel').textContent=`${formatTime(total)} total`;UI.$('#setProgressBar').style.width=`${Math.round(d.setProgress*1000)/10}%`;UI.$('#overallProgressBar').style.width=`${Math.round(d.overallProgress*1000)/10}%`;const idx=engine.timeline.items.indexOf(d.item);const next=engine.timeline.items[idx+1];UI.$('#upNextLabel').textContent=next?(next.type==='break'?'Break':`Set ${next.setIndex+1}`):'Complete';UI.$('#midpointLabel').textContent=d.currentPhase==='break'?'—':(d.midpointReached||d.setElapsed>=d.item.midpoint?'Reached':'Pending');UI.renderWorkoutTimeline(UI.$('#workoutTimeline'),engine.timeline,{index:idx,itemProgress:d.setProgress})}
function renderWorkoutControls(){const s=engine.state;UI.$('#mainWorkoutBtn').textContent=s==='running'?'Pause':s==='paused'?'Resume':s==='complete'?'Restart':'Start';}

window.addEventListener('keydown',e=>{if(e.code==='Space'&&UI.$('#workoutView').classList.contains('active')){e.preventDefault();if(engine.state==='running')engine.pause();else if(engine.state==='paused'||engine.state==='ready')engine.startOrResume();else if(engine.state==='complete')engine.restart(),engine.startOrResume()}});

init();
